services:
  node1:
    build: .
    environment:
      - NODE_ID=node1:5000
      - NODE_ADDR=node1:5000 # The address of the Raft node port
      - RAFT_BOOTSTRAP=true
      - RAFT_PEERS=node2:5000,node3:5000
    ports:
      - "8081:3000" # The address of the API server port
  node2:
    build: .
    environment:
      - NODE_ID=node2:5000
      - NODE_ADDR=node2:5000
      - RAFT_PEERS=node1:5000,node3:5000
    ports:
      - "8082:3000"
  node3:
    build: .
    environment:
      - NODE_ID=node3:5000
      - NODE_ADDR=node3:5000
      - RAFT_PEERS=node1:5000,node2:5000
    ports:
      - "8083:3000"